create table covid19_muckrock.metadata_stage (
	 id 	 text,
	 access 	 text,
	 asset_url 	 text,
	 canonical_url 	 text,
	 created_at 	 text,
	 data 	 text,
	 description 	 text,
	 edit_access 	 text,
	 file_hash 	 text,
	 noindex 	 text,
	 language 	 text,
	 organization 	 text,
	 original_extension 	 text,
	 page_count 	 text,
	 page_spec 	 text,
	 projects 	 text,
	 publish_at 	 text,
	 published_url 	 text,
	 related_article 	 text,
	 revision_control 	 text,
	 slug 	 text,
	 source 	 text,
	 status 	 text,
	 title 	 text,
	 updated_at 	 text,
	 userinfo 	 text
);
